In [1]:
import numpy as np
import pandas as pd
import tensorflow as tf

dataset = "./data/mushrooms.csv"
df = pd.read_csv(dataset)  # read DataSet

print("DataSet Size : {}".format(df.shape))
df.head(5)  # top 5 contents

/Users/joungwoongrhee/anaconda3/lib/python3.6/site-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters


DataSet Size : (8124, 23)


class cap-shape cap-surface cap-color bruises odor gill-attachment  \
0     p         x           s         n       t    p               f   
1     e         x           s         y       t    a               f   
2     e         b           s         w       t    l               f   
3     p         x           y         w       t    p               f   
4     e         x           s         g       f    n               f   

  gill-spacing gill-size gill-color   ...   stalk-surface-below-ring  \
0            c         n          k   ...                          s   
1            c         b          k   ...                          s   
2            c         b          n   ...                          s   
3            c         n          n   ...                          s   
4            w         b          k   ...                          s   

  stalk-color-above-ring stalk-color-below-ring veil-type veil-color  \
0                      w                      w         p          w   
1                      w                      w         p          w   
2                      w                      w         p          w   
3                      w                      w         p          w   
4                      w                      w         p          w   

  ring-number ring-type spore-print-color population habitat  
0           o         p                 k          s       u  
1           o         p                 n          n       g  
2           o         p                 n          n       m  
3           o         p                 k          s       u  
4           o         e                 n          a       g  

[5 rows x 23 columns]

In [2]:
# check the type of colums
df.dtypes 

class                       object
cap-shape                   object
cap-surface                 object
cap-color                   object
bruises                     object
odor                        object
gill-attachment             object
gill-spacing                object
gill-size                   object
gill-color                  object
stalk-shape                 object
stalk-root                  object
stalk-surface-above-ring    object
stalk-surface-below-ring    object
stalk-color-above-ring      object
stalk-color-below-ring      object
veil-type                   object
veil-color                  object
ring-number                 object
ring-type                   object
spore-print-color           object
population                  object
habitat                     object
dtype: object

In [3]:
df[df.isnull().any(axis=1)]

Empty DataFrame
Columns: [class, cap-shape, cap-surface, cap-color, bruises, odor, gill-attachment, gill-spacing, gill-size, gill-color, stalk-shape, stalk-root, stalk-surface-above-ring, stalk-surface-below-ring, stalk-color-above-ring, stalk-color-below-ring, veil-type, veil-color, ring-number, ring-type, spore-print-color, population, habitat]
Index: []

[0 rows x 23 columns]

In [4]:
# drop "class" column
df = df.drop('class', axis=1)
print(df.shape)
df.head()

(8124, 22)


cap-shape cap-surface cap-color bruises odor gill-attachment gill-spacing  \
0         x           s         n       t    p               f            c   
1         x           s         y       t    a               f            c   
2         b           s         w       t    l               f            c   
3         x           y         w       t    p               f            c   
4         x           s         g       f    n               f            w   

  gill-size gill-color stalk-shape   ...   stalk-surface-below-ring  \
0         n          k           e   ...                          s   
1         b          k           e   ...                          s   
2         b          n           e   ...                          s   
3         n          n           e   ...                          s   
4         b          k           t   ...                          s   

  stalk-color-above-ring stalk-color-below-ring veil-type veil-color  \
0                      w                      w         p          w   
1                      w                      w         p          w   
2                      w                      w         p          w   
3                      w                      w         p          w   
4                      w                      w         p          w   

  ring-number ring-type spore-print-color population habitat  
0           o         p                 k          s       u  
1           o         p                 n          n       g  
2           o         p                 n          n       m  
3           o         p                 k          s       u  
4           o         e                 n          a       g  

[5 rows x 22 columns]

In [5]:
# one-hot encoding for input data
for col in df.columns:
    df = pd.get_dummies(df, columns=[ col ])

df.head()

cap-shape_b  cap-shape_c  cap-shape_f  cap-shape_k  cap-shape_s  \
0            0            0            0            0            0   
1            0            0            0            0            0   
2            1            0            0            0            0   
3            0            0            0            0            0   
4            0            0            0            0            0   

   cap-shape_x  cap-surface_f  cap-surface_g  cap-surface_s  cap-surface_y  \
0            1              0              0              1              0   
1            1              0              0              1              0   
2            0              0              0              1              0   
3            1              0              0              0              1   
4            1              0              0              1              0   

     ...      population_s  population_v  population_y  habitat_d  habitat_g  \
0    ...                 1             0             0          0          0   
1    ...                 0             0             0          0          1   
2    ...                 0             0             0          0          0   
3    ...                 1             0             0          0          0   
4    ...                 0             0             0          0          1   

   habitat_l  habitat_m  habitat_p  habitat_u  habitat_w  
0          0          0          0          1          0  
1          0          0          0          0          0  
2          0          1          0          0          0  
3          0          0          0          1          0  
4          0          0          0          0          0  

[5 rows x 117 columns]

In [6]:
df.shape

(8124, 117)

In [7]:
# read csv again in order to make label data
df_class = pd.read_csv(dataset, usecols=['class'])

In [8]:
# one-hot encoding for label data
df_label = pd.get_dummies(df_class['class'])

df_label.head()

e  p
0  0  1
1  1  0
2  1  0
3  0  1
4  1  0

In [9]:
# drop "p" category column 
df_label = df_label.drop('p', axis=1)
df_label.head()

e
0  0
1  1
2  1
3  0
4  1

In [10]:
x_data = df.iloc[:]
y_data = df_label.iloc[:]

from sklearn.model_selection import train_test_split

# train data : test data = 80 : 20
x_train, x_test, y_train, y_test = \
        train_test_split(x_data, y_data, random_state=42, test_size=.2)

# Neural Network Model 1

* learning rate: 0.001
* optimizer: GradientDescentOptimizer 
* the number of layers: 3
* activation function: ReLU
* the number of nodes : [256, 128, 1]

In [11]:
X = tf.placeholder(tf.float32, shape=[None, 117], name='placeholder_X') # X
Y = tf.placeholder(tf.float32, shape=[None, 1], name='placeholder_Y')   # Y

w_init = tf.contrib.layers.variance_scaling_initializer(factor=1., mode='FAN_AVG', uniform=True)
b_init = tf.zeros_initializer()

W1 = tf.get_variable(shape=[117, 256], initializer=w_init, name='weight1')
b1 = tf.get_variable(shape=[256], initializer=b_init, name='bias1')

W2 = tf.get_variable(shape=[256, 128], initializer=w_init, name='weight2')
b2 = tf.get_variable(shape=[128], initializer=b_init, name='bias2')

W3 = tf.get_variable(shape=[128, 1], initializer=w_init, name='weight3')
b3 = tf.get_variable(shape=[1], initializer=b_init, name='bias3')

layer1 = tf.nn.relu(tf.add(tf.matmul(X, W1), b1)) 
layer2 = tf.nn.relu(tf.add(tf.matmul(layer1, W2), b2))
layer3 = tf.add(tf.matmul(layer2, W3), b3)

model = tf.sigmoid(layer3)

cost = tf.nn.sigmoid_cross_entropy_with_logits(logits=layer3, labels=Y)

train = tf.train.GradientDescentOptimizer(learning_rate=0.001).minimize(cost)

prediction = tf.cast(model > 0.5, dtype=tf.float32)
accuracy = tf.reduce_mean(tf.cast(tf.equal(prediction, Y), dtype=tf.float32))

with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())
    # Training
    for step in range(1001):
        cost_val, train_val = sess.run([cost, train],
                                       feed_dict={
                                           X: x_train,
                                           Y: y_train,
                                       })
        if step % 200 == 0:
            print('step: ', step, ' \n cost: \n', cost_val)
            print('accuracy: ', sess.run(accuracy, feed_dict={X: x_test, Y: y_test}), '\n')


step:  0  
 cost: 
 [[0.7692555 ]
 [0.69988483]
 [0.8659371 ]
 ...
 [0.758899  ]
 [0.6443548 ]
 [0.61703974]]
accuracy:  0.87015384 

step:  200  
 cost: 
 [[0.7293389]
 [0.7293389]
 [0.7293389]
 ...
 [0.6582197]
 [0.7293389]
 [0.6582197]]
accuracy:  0.5187692 

step:  400  
 cost: 
 [[0.7293388 ]
 [0.7293388 ]
 [0.7293388 ]
 ...
 [0.65821975]
 [0.7293388 ]
 [0.65821975]]
accuracy:  0.5187692 

step:  600  
 cost: 
 [[0.7293388 ]
 [0.7293388 ]
 [0.7293388 ]
 ...
 [0.65821975]
 [0.7293388 ]
 [0.65821975]]
accuracy:  0.5187692 

step:  800  
 cost: 
 [[0.7293389 ]
 [0.7293389 ]
 [0.7293389 ]
 ...
 [0.65821975]
 [0.7293389 ]
 [0.65821975]]
accuracy:  0.5187692 

step:  1000  
 cost: 
 [[0.7293389]
 [0.7293389]
 [0.7293389]
 ...
 [0.6582197]
 [0.7293389]
 [0.6582197]]
accuracy:  0.5187692 



# Neural Network Model 2

* learning rate: 0.00001
* optimizer: GradientDescentOptimizer 
* the number of layers: 3
* activation function: ReLU
* the number of nodes : [256, 128, 1]

In [11]:
X = tf.placeholder(tf.float32, shape=[None, 117], name='placeholder_X') # X
Y = tf.placeholder(tf.float32, shape=[None, 1], name='placeholder_Y')   # Y

w_init = tf.contrib.layers.variance_scaling_initializer(factor=1., mode='FAN_AVG', uniform=True)
b_init = tf.zeros_initializer()

W1 = tf.get_variable(shape=[117, 256], initializer=w_init, name='weight1')
b1 = tf.get_variable(shape=[256], initializer=b_init, name='bias1')

W2 = tf.get_variable(shape=[256, 128], initializer=w_init, name='weight2')
b2 = tf.get_variable(shape=[128], initializer=b_init, name='bias2')

W3 = tf.get_variable(shape=[128, 1], initializer=w_init, name='weight3')
b3 = tf.get_variable(shape=[1], initializer=b_init, name='bias3')

layer1 = tf.nn.relu(tf.add(tf.matmul(X, W1), b1)) 
layer2 = tf.nn.relu(tf.add(tf.matmul(layer1, W2), b2))
layer3 = tf.add(tf.matmul(layer2, W3), b3)

model = tf.sigmoid(layer3)

cost = tf.nn.sigmoid_cross_entropy_with_logits(logits=layer3, labels=Y)

train = tf.train.GradientDescentOptimizer(learning_rate=0.00001).minimize(cost)

prediction = tf.cast(model > 0.5, dtype=tf.float32)
accuracy = tf.reduce_mean(tf.cast(tf.equal(prediction, Y), dtype=tf.float32))

with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())
    # Training
    for step in range(1001):
        cost_val, train_val = sess.run([cost, train],
                                       feed_dict={
                                           X: x_train,
                                           Y: y_train,
                                       })
        if step % 200 == 0:
            print('step: ', step, ' \n cost: \n', cost_val)
            print('accuracy: ', sess.run(accuracy, feed_dict={X: x_test, Y: y_test}), '\n')


step:  0  
 cost: 
 [[0.51242393]
 [0.7302965 ]
 [0.6488372 ]
 ...
 [0.64594877]
 [0.634812  ]
 [0.6184091 ]]
accuracy:  0.70584613 

step:  200  
 cost: 
 [[0.00190521]
 [0.00269455]
 [0.01214727]
 ...
 [0.03194896]
 [0.00381264]
 [0.01215034]]
accuracy:  0.9969231 

step:  400  
 cost: 
 [[0.00052259]
 [0.00066814]
 [0.00392593]
 ...
 [0.00626487]
 [0.00111507]
 [0.00206302]]
accuracy:  0.9987692 

step:  600  
 cost: 
 [[0.00023788]
 [0.00029621]
 [0.00185733]
 ...
 [0.00224595]
 [0.00053345]
 [0.00069028]]
accuracy:  0.99938464 

step:  800  
 cost: 
 [[0.00013625]
 [0.00016104]
 [0.00107907]
 ...
 [0.0010657 ]
 [0.00031694]
 [0.00031415]]
accuracy:  1.0 

step:  1000  
 cost: 
 [[8.8201363e-05]
 [9.8194250e-05]
 [6.9850887e-04]
 ...
 [6.0085510e-04]
 [2.0958511e-04]
 [1.7167808e-04]]
accuracy:  1.0 



# Neural Network Model 3

* learning rate: 0.001
* optimizer: GradientDescentOptimizer 
* the number of layers: 3
* activation function: sigmoid
* the number of nodes : [256, 128, 1]

In [11]:
X = tf.placeholder(tf.float32, shape=[None, 117], name='placeholder_X') # X
Y = tf.placeholder(tf.float32, shape=[None, 1], name='placeholder_Y')   # Y

w_init = tf.contrib.layers.variance_scaling_initializer(factor=1., mode='FAN_AVG', uniform=True)
b_init = tf.zeros_initializer()

W1 = tf.get_variable(shape=[117, 256], initializer=w_init, name='weight1')
b1 = tf.get_variable(shape=[256], initializer=b_init, name='bias1')

W2 = tf.get_variable(shape=[256, 128], initializer=w_init, name='weight2')
b2 = tf.get_variable(shape=[128], initializer=b_init, name='bias2')

W3 = tf.get_variable(shape=[128, 1], initializer=w_init, name='weight3')
b3 = tf.get_variable(shape=[1], initializer=b_init, name='bias3')

layer1 = tf.sigmoid(tf.add(tf.matmul(X, W1), b1)) 
layer2 = tf.sigmoid(tf.add(tf.matmul(layer1, W2), b2))
layer3 = tf.add(tf.matmul(layer2, W3), b3)

model = tf.sigmoid(layer3)

cost = tf.nn.sigmoid_cross_entropy_with_logits(logits=layer3, labels=Y)

train = tf.train.GradientDescentOptimizer(learning_rate=0.001).minimize(cost)

prediction = tf.cast(model > 0.5, dtype=tf.float32)
accuracy = tf.reduce_mean(tf.cast(tf.equal(prediction, Y), dtype=tf.float32))

with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())
    # Training
    for step in range(1001):
        cost_val, train_val = sess.run([cost, train],
                                       feed_dict={
                                           X: x_train,
                                           Y: y_train,
                                       })
        if step % 200 == 0:
            print('step: ', step, ' \n cost: \n', cost_val)
            print('accuracy: ', sess.run(accuracy, feed_dict={X: x_test, Y: y_test}), '\n')


step:  0  
 cost: 
 [[0.44752258]
 [0.44883338]
 [0.45172292]
 ...
 [1.0007902 ]
 [0.4526772 ]
 [0.9987422 ]]
accuracy:  0.5187692 

step:  200  
 cost: 
 [[1.3126280e-05]
 [1.6809912e-07]
 [1.0233104e-04]
 ...
 [4.0778060e-02]
 [3.7136224e-06]
 [1.6965535e-02]]
accuracy:  0.9895385 

step:  400  
 cost: 
 [[9.5025753e-06]
 [2.7689564e-08]
 [5.7595997e-05]
 ...
 [1.5996858e-03]
 [1.4060644e-06]
 [9.7848242e-04]]
accuracy:  1.0 

step:  600  
 cost: 
 [[5.4086249e-06]
 [1.0383012e-08]
 [4.8235594e-05]
 ...
 [6.9400121e-04]
 [8.1880614e-07]
 [4.4125455e-04]]
accuracy:  1.0 

step:  800  
 cost: 
 [[3.4143766e-06]
 [5.3410072e-09]
 [3.4584027e-05]
 ...
 [4.3668807e-04]
 [5.0647651e-07]
 [2.8504588e-04]]
accuracy:  1.0 

step:  1000  
 cost: 
 [[2.3875195e-06]
 [3.2936889e-09]
 [2.5606345e-05]
 ...
 [3.1742148e-04]
 [3.4640036e-07]
 [2.1111073e-04]]
accuracy:  1.0 



# Neural Network Model 4

* learning rate: 0.001
* optimizer: AdamOptimizer 
* the number of layers: 3
* activation function: sigmoid
* the number of nodes : [256, 128, 1]

In [11]:
# learning rate: 0.001
# optimizer: AdamOptimizer 
# the number of layers: 3
# activation function: sigmoid

X = tf.placeholder(tf.float32, shape=[None, 117], name='placeholder_X') # X
Y = tf.placeholder(tf.float32, shape=[None, 1], name='placeholder_Y')   # Y

w_init = tf.contrib.layers.variance_scaling_initializer(factor=1., mode='FAN_AVG', uniform=True)
b_init = tf.zeros_initializer()

W1 = tf.get_variable(shape=[117, 256], initializer=w_init, name='weight1')
b1 = tf.get_variable(shape=[256], initializer=b_init, name='bias1')

W2 = tf.get_variable(shape=[256, 128], initializer=w_init, name='weight2')
b2 = tf.get_variable(shape=[128], initializer=b_init, name='bias2')

W3 = tf.get_variable(shape=[128, 1], initializer=w_init, name='weight3')
b3 = tf.get_variable(shape=[1], initializer=b_init, name='bias3')

layer1 = tf.sigmoid(tf.add(tf.matmul(X, W1), b1)) 
layer2 = tf.sigmoid(tf.add(tf.matmul(layer1, W2), b2))
layer3 = tf.add(tf.matmul(layer2, W3), b3)

model = tf.sigmoid(layer3)

cost = tf.nn.sigmoid_cross_entropy_with_logits(logits=layer3, labels=Y)

train = tf.train.AdamOptimizer(learning_rate=0.001).minimize(cost)

prediction = tf.cast(model > 0.5, dtype=tf.float32)
accuracy = tf.reduce_mean(tf.cast(tf.equal(prediction, Y), dtype=tf.float32))

with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())
    # Training
    for step in range(1001):
        cost_val, train_val = sess.run([cost, train],
                                       feed_dict={
                                           X: x_train,
                                           Y: y_train,
                                       })
        if step % 200 == 0:
            print('step: ', step, ' \n cost: \n', cost_val)
            print('accuracy: ', sess.run(accuracy, feed_dict={X: x_test, Y: y_test}), '\n')


step:  0  
 cost: 
 [[0.65596616]
 [0.68308544]
 [0.6597829 ]
 ...
 [0.73353624]
 [0.6649686 ]
 [0.73344624]]
accuracy:  0.5187692 

step:  200  
 cost: 
 [[0.00113983]
 [0.00064367]
 [0.00497217]
 ...
 [0.00072371]
 [0.00124998]
 [0.00034759]]
accuracy:  0.9987692 

step:  400  
 cost: 
 [[2.3820031e-04]
 [1.5600122e-04]
 [1.2663440e-03]
 ...
 [1.4049468e-04]
 [4.4612712e-04]
 [5.2400097e-05]]
accuracy:  1.0 

step:  600  
 cost: 
 [[1.00116165e-04]
 [6.56907941e-05]
 [5.76477905e-04]
 ...
 [5.66528652e-05]
 [2.34935971e-04]
 [2.13036528e-05]]
accuracy:  1.0 

step:  800  
 cost: 
 [[5.5486391e-05]
 [3.6098700e-05]
 [3.3399416e-04]
 ...
 [3.0528361e-05]
 [1.4740144e-04]
 [1.1933308e-05]]
accuracy:  1.0 

step:  1000  
 cost: 
 [[3.54424519e-05]
 [2.28942954e-05]
 [2.19312991e-04]
 ...
 [1.91732070e-05]
 [1.01914324e-04]
 [7.78774302e-06]]
accuracy:  1.0 



# Neural Network Model 5

* learning rate: 0.001
* optimizer: AdamOptimizer 
* the number of layers: 3
* activation function: sigmoid
* the number of nodes : [64, 32, 1]

In [11]:
# learning rate: 0.001
# optimizer: AdamOptimizer 
# the number of layers: 3
# activation function: sigmoid
# change the number of nodes

X = tf.placeholder(tf.float32, shape=[None, 117], name='placeholder_X') # X
Y = tf.placeholder(tf.float32, shape=[None, 1], name='placeholder_Y')   # Y

w_init = tf.contrib.layers.variance_scaling_initializer(factor=1., mode='FAN_AVG', uniform=True)
b_init = tf.zeros_initializer()

W1 = tf.get_variable(shape=[117, 64], initializer=w_init, name='weight1')
b1 = tf.get_variable(shape=[64], initializer=b_init, name='bias1')

W2 = tf.get_variable(shape=[64, 32], initializer=w_init, name='weight2')
b2 = tf.get_variable(shape=[32], initializer=b_init, name='bias2')

W3 = tf.get_variable(shape=[32, 1], initializer=w_init, name='weight3')
b3 = tf.get_variable(shape=[1], initializer=b_init, name='bias3')

layer1 = tf.sigmoid(tf.add(tf.matmul(X, W1), b1)) 
layer2 = tf.sigmoid(tf.add(tf.matmul(layer1, W2), b2))
layer3 = tf.add(tf.matmul(layer2, W3), b3)

model = tf.sigmoid(layer3)

cost = tf.nn.sigmoid_cross_entropy_with_logits(logits=layer3, labels=Y)

train = tf.train.AdamOptimizer(learning_rate=0.001).minimize(cost)

prediction = tf.cast(model > 0.5, dtype=tf.float32)
accuracy = tf.reduce_mean(tf.cast(tf.equal(prediction, Y), dtype=tf.float32))

with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())
    # Training
    for step in range(1001):
        cost_val, train_val = sess.run([cost, train],
                                       feed_dict={
                                           X: x_train,
                                           Y: y_train,
                                       })
        if step % 200 == 0:
            print('step: ', step, ' \n cost: \n', cost_val)
            print('accuracy: ', sess.run(accuracy, feed_dict={X: x_test, Y: y_test}), '\n')


step:  0  
 cost: 
 [[0.24955846]
 [0.24723107]
 [0.2499592 ]
 ...
 [1.4792246 ]
 [0.24528597]
 [1.5010474 ]]
accuracy:  0.48123077 

step:  200  
 cost: 
 [[0.03573035]
 [0.02696766]
 [0.04737439]
 ...
 [0.06898206]
 [0.02779595]
 [0.09236758]]
accuracy:  0.9790769 

step:  400  
 cost: 
 [[0.00781997]
 [0.00545064]
 [0.01280733]
 ...
 [0.01431018]
 [0.00681659]
 [0.01326123]]
accuracy:  0.9987692 

step:  600  
 cost: 
 [[0.00339235]
 [0.00257845]
 [0.00565905]
 ...
 [0.00689744]
 [0.00336334]
 [0.00613914]]
accuracy:  1.0 

step:  800  
 cost: 
 [[0.0019335 ]
 [0.00154986]
 [0.0031937 ]
 ...
 [0.00423958]
 [0.00206889]
 [0.00374622]]
accuracy:  1.0 

step:  1000  
 cost: 
 [[0.00126411]
 [0.0010408 ]
 [0.00208032]
 ...
 [0.00292155]
 [0.0014152 ]
 [0.00258757]]
accuracy:  1.0 

