In [1]:
import os
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline

os.chdir('/Users/joungwoongrhee/workspace/naver18/Super-Mario')
os.getcwd()

df = pd.read_csv('./data/mushrooms.csv')
df.head()

class cap-shape cap-surface cap-color bruises odor gill-attachment  \
0     p         x           s         n       t    p               f   
1     e         x           s         y       t    a               f   
2     e         b           s         w       t    l               f   
3     p         x           y         w       t    p               f   
4     e         x           s         g       f    n               f   

  gill-spacing gill-size gill-color   ...   stalk-surface-below-ring  \
0            c         n          k   ...                          s   
1            c         b          k   ...                          s   
2            c         b          n   ...                          s   
3            c         n          n   ...                          s   
4            w         b          k   ...                          s   

  stalk-color-above-ring stalk-color-below-ring veil-type veil-color  \
0                      w                      w         p          w   
1                      w                      w         p          w   
2                      w                      w         p          w   
3                      w                      w         p          w   
4                      w                      w         p          w   

  ring-number ring-type spore-print-color population habitat  
0           o         p                 k          s       u  
1           o         p                 n          n       g  
2           o         p                 n          n       m  
3           o         p                 k          s       u  
4           o         e                 n          a       g  

[5 rows x 23 columns]

In [7]:
cols = df.columns

category_list = []
for col in cols:
    category_list.append(df[col].unique())
    
category_list

[array(['p', 'e'], dtype=object),
 array(['x', 'b', 's', 'f', 'k', 'c'], dtype=object),
 array(['s', 'y', 'f', 'g'], dtype=object),
 array(['n', 'y', 'w', 'g', 'e', 'p', 'b', 'u', 'c', 'r'], dtype=object),
 array(['t', 'f'], dtype=object),
 array(['p', 'a', 'l', 'n', 'f', 'c', 'y', 's', 'm'], dtype=object),
 array(['f', 'a'], dtype=object),
 array(['c', 'w'], dtype=object),
 array(['n', 'b'], dtype=object),
 array(['k', 'n', 'g', 'p', 'w', 'h', 'u', 'e', 'b', 'r', 'y', 'o'],
       dtype=object),
 array(['e', 't'], dtype=object),
 array(['e', 'c', 'b', 'r', '?'], dtype=object),
 array(['s', 'f', 'k', 'y'], dtype=object),
 array(['s', 'f', 'y', 'k'], dtype=object),
 array(['w', 'g', 'p', 'n', 'b', 'e', 'o', 'c', 'y'], dtype=object),
 array(['w', 'p', 'g', 'b', 'n', 'e', 'y', 'o', 'c'], dtype=object),
 array(['p'], dtype=object),
 array(['w', 'n', 'o', 'y'], dtype=object),
 array(['o', 't', 'n'], dtype=object),
 array(['p', 'e', 'l', 'f', 'n'], dtype=object),
 array(['k', 'n', 'u', 'h', 

In [8]:
len(category_list)

23

In [12]:
# unique는 sorting이 안됨....
category_list_sorted = []
for i in range(len(category_list)):
    tmp_list = []
    for j in range(len(category_list[i])):
        tmp_list.append(category_list[i][j])
    
    tmp_list.sort()
    category_list_sorted.append(tmp_list)
    
category_list_sorted

[['e', 'p'],
 ['b', 'c', 'f', 'k', 's', 'x'],
 ['f', 'g', 's', 'y'],
 ['b', 'c', 'e', 'g', 'n', 'p', 'r', 'u', 'w', 'y'],
 ['f', 't'],
 ['a', 'c', 'f', 'l', 'm', 'n', 'p', 's', 'y'],
 ['a', 'f'],
 ['c', 'w'],
 ['b', 'n'],
 ['b', 'e', 'g', 'h', 'k', 'n', 'o', 'p', 'r', 'u', 'w', 'y'],
 ['e', 't'],
 ['?', 'b', 'c', 'e', 'r'],
 ['f', 'k', 's', 'y'],
 ['f', 'k', 's', 'y'],
 ['b', 'c', 'e', 'g', 'n', 'o', 'p', 'w', 'y'],
 ['b', 'c', 'e', 'g', 'n', 'o', 'p', 'w', 'y'],
 ['p'],
 ['n', 'o', 'w', 'y'],
 ['n', 'o', 't'],
 ['e', 'f', 'l', 'n', 'p'],
 ['b', 'h', 'k', 'n', 'o', 'r', 'u', 'w', 'y'],
 ['a', 'c', 'n', 's', 'v', 'y'],
 ['d', 'g', 'l', 'm', 'p', 'u', 'w']]

In [18]:
[i for i in range(2)]

[0, 1]

In [22]:
category_list_sorted_num = []

for one_col in category_list_sorted:
    tmp = [i for i in range(len(one_col))]
    unit = []
    for j in tmp:
        unit.append([j])
    category_list_sorted_num.append(unit)
category_list_sorted_num

[[[0], [1]],
 [[0], [1], [2], [3], [4], [5]],
 [[0], [1], [2], [3]],
 [[0], [1], [2], [3], [4], [5], [6], [7], [8], [9]],
 [[0], [1]],
 [[0], [1], [2], [3], [4], [5], [6], [7], [8]],
 [[0], [1]],
 [[0], [1]],
 [[0], [1]],
 [[0], [1], [2], [3], [4], [5], [6], [7], [8], [9], [10], [11]],
 [[0], [1]],
 [[0], [1], [2], [3], [4]],
 [[0], [1], [2], [3]],
 [[0], [1], [2], [3]],
 [[0], [1], [2], [3], [4], [5], [6], [7], [8]],
 [[0], [1], [2], [3], [4], [5], [6], [7], [8]],
 [[0]],
 [[0], [1], [2], [3]],
 [[0], [1], [2]],
 [[0], [1], [2], [3], [4]],
 [[0], [1], [2], [3], [4], [5], [6], [7], [8]],
 [[0], [1], [2], [3], [4], [5]],
 [[0], [1], [2], [3], [4], [5], [6]]]

In [33]:
print(category_list_sorted_num[0])
print(len(category_list_sorted_num[0]))

[[0], [1]]
2


In [42]:
from sklearn.preprocessing import OneHotEncoder
ohe = OneHotEncoder()

test = np.array(category_list_sorted_num[1])

In [43]:
ohe.fit(test)
ohe.n_values_, ohe.feature_indices_, ohe.active_features_

(array([6]), array([0, 6]), array([0, 1, 2, 3, 4, 5]))

In [44]:
ohe.transform(test).toarray()

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])

test 끝

In [50]:
np.array([[1]], dtype=float)

array([[1.]])

In [51]:
np.array([[1,0],[0,1]], dtype=float)

array([[1., 0.],
       [0., 1.]])

In [52]:
one_hot_list = []
for one_col in category_list_sorted_num:
    if len(one_col) == 1:
        one_hot_list.append(np.array([[1]], dtype=float))
    elif len(one_col) == 2:        
        one_hot_list.append(np.array([[1,0],[0,1]], dtype=float))
    else :
        ohe.fit(one_col)
        ohe.n_values_, ohe.feature_indices_, ohe.active_features_
        tmp = ohe.transform(one_col).toarray()
        one_hot_list.append(tmp)

one_hot_list

[array([[1., 0.],
        [0., 1.]]), array([[1., 0., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0., 0.],
        [0., 0., 1., 0., 0., 0.],
        [0., 0., 0., 1., 0., 0.],
        [0., 0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 0., 1.]]), array([[1., 0., 0., 0.],
        [0., 1., 0., 0.],
        [0., 0., 1., 0.],
        [0., 0., 0., 1.]]), array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]]), array([[1., 0.],
        [0., 1.]]), array([[1., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 1., 0.

In [53]:
type(one_hot_list)

list

In [54]:
one_hot_list[0]

array([[1., 0.],
       [0., 1.]])

In [55]:
category_list_sorted[0]

['e', 'p']

In [60]:
cols = df.columns
one_hot_dict = {}
one_hot_dict[cols[0] + '_' + category_list_sorted[0][0]] = one_hot_list[0][0]

In [61]:
one_hot_dict

{'class_e': array([1., 0.])}

In [62]:
cols = df.columns
one_hot_dict = {}

for i in range(len(one_hot_list)):
    for j in range(len(one_hot_list[i])):
        one_hot_dict[cols[i] + '_' + category_list_sorted[i][j]] = one_hot_list[i][j]

one_hot_dict

{'bruises_f': array([1., 0.]),
 'bruises_t': array([0., 1.]),
 'cap-color_b': array([1., 0., 0., 0., 0., 0., 0., 0., 0., 0.]),
 'cap-color_c': array([0., 1., 0., 0., 0., 0., 0., 0., 0., 0.]),
 'cap-color_e': array([0., 0., 1., 0., 0., 0., 0., 0., 0., 0.]),
 'cap-color_g': array([0., 0., 0., 1., 0., 0., 0., 0., 0., 0.]),
 'cap-color_n': array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.]),
 'cap-color_p': array([0., 0., 0., 0., 0., 1., 0., 0., 0., 0.]),
 'cap-color_r': array([0., 0., 0., 0., 0., 0., 1., 0., 0., 0.]),
 'cap-color_u': array([0., 0., 0., 0., 0., 0., 0., 1., 0., 0.]),
 'cap-color_w': array([0., 0., 0., 0., 0., 0., 0., 0., 1., 0.]),
 'cap-color_y': array([0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]),
 'cap-shape_b': array([1., 0., 0., 0., 0., 0.]),
 'cap-shape_c': array([0., 1., 0., 0., 0., 0.]),
 'cap-shape_f': array([0., 0., 1., 0., 0., 0.]),
 'cap-shape_k': array([0., 0., 0., 1., 0., 0.]),
 'cap-shape_s': array([0., 0., 0., 0., 1., 0.]),
 'cap-shape_x': array([0., 0., 0., 0., 0., 

In [65]:
one_hot_dict['bruises_f'][1]

0.0

In [71]:
def changer_by_dict(value, col_name):
    key = col_name + '_' + value
    return one_hot_dict[key] 

In [74]:
import copy
df_test = copy.deepcopy(df)

df_test['class'] = df_test['class'].apply(changer_by_dict, col_name='class')
df_test.head()

class cap-shape cap-surface cap-color bruises odor gill-attachment  \
0  [0.0, 1.0]         x           s         n       t    p               f   
1  [1.0, 0.0]         x           s         y       t    a               f   
2  [1.0, 0.0]         b           s         w       t    l               f   
3  [0.0, 1.0]         x           y         w       t    p               f   
4  [1.0, 0.0]         x           s         g       f    n               f   

  gill-spacing gill-size gill-color   ...   stalk-surface-below-ring  \
0            c         n          k   ...                          s   
1            c         b          k   ...                          s   
2            c         b          n   ...                          s   
3            c         n          n   ...                          s   
4            w         b          k   ...                          s   

  stalk-color-above-ring stalk-color-below-ring veil-type veil-color  \
0                      w                      w         p          w   
1                      w                      w         p          w   
2                      w                      w         p          w   
3                      w                      w         p          w   
4                      w                      w         p          w   

  ring-number ring-type spore-print-color population habitat  
0           o         p                 k          s       u  
1           o         p                 n          n       g  
2           o         p                 n          n       m  
3           o         p                 k          s       u  
4           o         e                 n          a       g  

[5 rows x 23 columns]

In [75]:
cols = df.columns
for col in cols:
    df[col] = df[col].apply(changer_by_dict, col_name=col)

df.head()

class                       cap-shape           cap-surface  \
0  [0.0, 1.0]  [0.0, 0.0, 0.0, 0.0, 0.0, 1.0]  [0.0, 0.0, 1.0, 0.0]   
1  [1.0, 0.0]  [0.0, 0.0, 0.0, 0.0, 0.0, 1.0]  [0.0, 0.0, 1.0, 0.0]   
2  [1.0, 0.0]  [1.0, 0.0, 0.0, 0.0, 0.0, 0.0]  [0.0, 0.0, 1.0, 0.0]   
3  [0.0, 1.0]  [0.0, 0.0, 0.0, 0.0, 0.0, 1.0]  [0.0, 0.0, 0.0, 1.0]   
4  [1.0, 0.0]  [0.0, 0.0, 0.0, 0.0, 0.0, 1.0]  [0.0, 0.0, 1.0, 0.0]   

                                           cap-color     bruises  \
0  [0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, ...  [0.0, 1.0]   
1  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...  [0.0, 1.0]   
2  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, ...  [0.0, 1.0]   
3  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, ...  [0.0, 1.0]   
4  [0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...  [1.0, 0.0]   

                                            odor gill-attachment gill-spacing  \
0  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0]      [0.0, 1.0]   [1.0, 0.0]   
1  [1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]      [0.0, 1.0]   [1.0, 0.0]   
2  [0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0]      [0.0, 1.0]   [1.0, 0.0]   
3  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0]      [0.0, 1.0]   [1.0, 0.0]   
4  [0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0]      [0.0, 1.0]   [0.0, 1.0]   

    gill-size                                         gill-color  \
0  [0.0, 1.0]  [0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, ...   
1  [1.0, 0.0]  [0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, ...   
2  [1.0, 0.0]  [0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, ...   
3  [0.0, 1.0]  [0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, ...   
4  [1.0, 0.0]  [0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, ...   

                  ...                  stalk-surface-below-ring  \
0                 ...                      [0.0, 0.0, 1.0, 0.0]   
1                 ...                      [0.0, 0.0, 1.0, 0.0]   
2                 ...                      [0.0, 0.0, 1.0, 0.0]   
3                 ...                      [0.0, 0.0, 1.0, 0.0]   
4                 ...                      [0.0, 0.0, 1.0, 0.0]   

                          stalk-color-above-ring  \
0  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0]   
1  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0]   
2  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0]   
3  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0]   
4  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0]   

                          stalk-color-below-ring veil-type  \
0  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0]     [1.0]   
1  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0]     [1.0]   
2  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0]     [1.0]   
3  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0]     [1.0]   
4  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0]     [1.0]   

             veil-color      ring-number                  ring-type  \
0  [0.0, 0.0, 1.0, 0.0]  [0.0, 1.0, 0.0]  [0.0, 0.0, 0.0, 0.0, 1.0]   
1  [0.0, 0.0, 1.0, 0.0]  [0.0, 1.0, 0.0]  [0.0, 0.0, 0.0, 0.0, 1.0]   
2  [0.0, 0.0, 1.0, 0.0]  [0.0, 1.0, 0.0]  [0.0, 0.0, 0.0, 0.0, 1.0]   
3  [0.0, 0.0, 1.0, 0.0]  [0.0, 1.0, 0.0]  [0.0, 0.0, 0.0, 0.0, 1.0]   
4  [0.0, 0.0, 1.0, 0.0]  [0.0, 1.0, 0.0]  [1.0, 0.0, 0.0, 0.0, 0.0]   

                               spore-print-color  \
0  [0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]   
1  [0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0]   
2  [0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0]   
3  [0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]   
4  [0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0]   

                       population                              habitat  
0  [0.0, 0.0, 0.0, 1.0, 0.0, 0.0]  [0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0]  
1  [0.0, 0.0, 1.0, 0.0, 0.0, 0.0]  [0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0]  
2  [0.0, 0.0, 1.0, 0.0, 0.0, 0.0]  [0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0]  
3  [0.0, 0.0, 0.0, 1.0, 0.0, 0.0]  [0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0]  
4  [1.0, 0.0, 0.0, 0.0, 0.0, 0.0]  [0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0]  

[5 rows 

In [76]:
df.to_csv('./one_hot.csv')

# 안씀

In [30]:
np.zeros(4)
len(np.zeros(4))
a = np.zeros(4)
a[2] =1 
a

array([0., 0., 1., 0.])

In [ ]:
cols = df.columns

one_hot_dict = {}

for i in range(len(category_list_sorted)):
    col_name = cols[i]
    how_many = len(category_list_sorted[i])
    
    if how_many == 2:
        for j in range(2):
            name = col_name + '_' + category_list_sorted[i][j]
            key = 
            one_hot_dict[name] = 
            category_list[i][0]